services:
  - type: web
    name: retailsense-ai-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn API.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RETAILSENSE_PROJECT_ROOT
        value: /opt/render/project/src
      - key: RETAILSENSE_ML_DIR
        value: /opt/render/project/src/Machine-Learning
      - key: RETAILSENSE_DL_DIR
        value: /opt/render/project/src/Deep-Learning
      - key: RETAILSENSE_SENTIMENT_MODEL_ID
        value: nlptown/bert-base-multilingual-uncased-sentiment
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
